name = "proxy-worker-cloudflare"
main = "src/index.js"
compatibility_date = "2025-04-25"

# Routes cho các domain
routes = [
  { pattern = "servtech.site/*", zone_name = "servtech.site" },
  { pattern = "www.servtech.site/*", zone_name = "servtech.site" }
]

# Binding KV Namespace
[[kv_namespaces]]
binding = "DOMAIN_PARTY_ID_MAPPING"
id = "" # ID sẽ được cung cấp qua Dashboard hoặc Wrangler CLI

# Biến môi trường
[vars]
DEBUG = "false"
TARGET_BASE = "https://refactor.d2s3bo1qpvtzn8.amplifyapp.com"
VALIDATE_PARTY_ID = "true" # Bật kiểm tra định dạng UUID cho X-Party-Id từ client