name = "proxy-worker-cloudflare"
     account_id = "fda3abf6924443478d3932e9b590012f"
     main = "src/index.js"
     compatibility_date = "2025-04-25"
     routes = [
       { pattern = "servtech.site/*", zone_name = "servtech.site" },
     ]